### ISSUE TITLE
Missing string definitions

### ISSUE THREAD

**Issue by ewallah** [antriver/moodle-block_search#13]
Invalid get_string() identifier: 'cachedef_user_searches' or component 'block_search'. Perhaps you are missing $string['cachedef_user_searches'] = ''; in /blocks/search/lang/en/block_search.php?
line 348 of /lib/classes/string_manager_standard.php: call to debugging()
line 9774 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 9808 of /lib/moodlelib.php: call to lang_string->get_string()
line ? of unknownfile: call to lang_string->__toString()
line 212 of /lib/classes/collator.php: call to Collator->asort()
line 322 of /lib/classes/collator.php: call to core_collator::asort()
line 238 of /cache/renderer.php: call to core_collator::asort_array_of_arrays_by_key()
line 303 of /cache/admin.php: call to core_cache_renderer->definition_summaries()
Invalid get_string() identifier: 'cachedef_main' or component 'block_search'. Perhaps you are missing $string['cachedef_main'] = ''; in /blocks/search/lang/en/block_search.php?
line 348 of /lib/classes/string_manager_standard.php: call to debugging()
line 9774 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 9808 of /lib/moodlelib.php: call to lang_string->get_string()
line ? of unknownfile: call to lang_string->__toString()
line 212 of /lib/classes/collator.php: call to Collator->asort()
line 322 of /lib/classes/collator.php: call to core_collator::asort()
line 238 of /cache/renderer.php: call to core_collator::asort_array_of_arrays_by_key()
line 303 of /cache/admin.php: call to core_cache_renderer->definition_summaries()

**Comment by antriver** [comment]
Hi,
This has been fixed by @nadavkav

**Comment by nadavkav** [comment]
Thanks
