### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by relecand** [antriver/moodle-block_search#16]
$string['advanced_search_desc'] = 'Fügen Sie diese Worte zu Ihrer Suche hinzu, um die Ergebnisse zu verfeinern.';
$string['advanced_search_exact_desc'] = 'Finden Sie Ergebnisse mit dieser <strong>exakten Phrase</strong>';
$string['advanced_search_exclude_desc'] = 'Finden Sie Ergebnisse, die dieses Wort <strong>nicht</strong> enthalten.';
$string['advanced_search_exclude_example'] = '-Wort';
$string['advanced_search_wildcard_desc'] = '* ist ein <strong>Platzhalter</strong>. Das würde z.B. "word" und "weird" finden.';
$string['displaying_took'] = 'Resultate zeigen hat <strong>{$a}</strong> Sekunden gedauert.';
$string['error_query_too_short'] = 'Bitte geben Sie einen Suchbegriff mit mindestens {$a} Zeichen ein.';
$string['hidden_not_available'] = 'Diese Ressource ist nicht für Sie verfügbar.';
$string['include_hidden_results'] = 'Zeigen von Ergebnissen, auf die ich keinen Zugriff habe.';
$string['no_results'] = 'Sorry, es gab keine Ergebnisse zu Ihrer Suche.';
$string['search_all_of_site'] = 'Globale Suche in {$a}';
$string['search_in_course'] = 'Suche nur in {$a}';
$string['search_input_text_block'] = 'Diesen Kurs suchen';
$string['search_input_text_page'] = 'Finde Kurse, Aktivitäten oder Dokumente';
$string['search:search'] = 'Führen Sie eine Suche durch';
$string['settings_allow_no_access_desc'] = 'Benutzer erlauben, Suchergebnisse zu sehen, auf die sie keinen Zugriff haben: "Zeigen von Ergebnissen, auf die ich kein Zugriff habe." (Das erlaubt ihnen nicht$
$string['settings_log_searches_desc'] = 'Sollen Suchanfragen in den Moodle-Protokollen gelogged werden?';
$string['settings_log_searches_name'] = 'Log Suche';
$string['settings_results_per_page_desc'] = 'Wie viele Suchergebnisse pro Seite anzeigen';
$string['settings_search_files_in_folders_desc'] = 'Soll versucht werden, Dateien innerhalb von "Ordner" Aktivitäten/Ressourcen zu finden?';
$string['try_full_search'] = 'Wollten Sie die gesamte Seite durchsuchen anstatt nur diesen Kurs?';

**Comment by antriver** [comment]
Thank you!
I've added these
